x=ones(1,8);
n=0:length(x)-1;
t0=clock;
[m1,a1]=dft1(x);
subplot(321),stem(n,m1,'.');
title('用dft1实现 mag');
subplot(322),stem(n,a1,'.');
title('angle');
t1=etime(clock,t0);
t0=clock;
[m2,a2]=dft2(x);
subplot(323),stem(n,m2,'.');
title('用dft2实现 mag');
subplot(324),stem(n,a2,'.');
title('angle');
t2=etime(clock,t0);
t0=clock;
xk=fft(x);
subplot(325),stem(n,abs(xk),'.');
title('用FFT实现 mag');
subplot(326),stem(n,angle(xk),'.');
title('angle');
t3=etime(clock,t0);
figure;
subplot(311),stem(t1,'.');ylabel('单位：s');title('用dft1实现');
subplot(312),stem(t2,'.');ylabel('单位：s');title('用dft2实现');
subplot(313),stem(t3,'.');ylabel('单位：s');title('用FFT实现');