f=32; 
dt=1/f; 
N=32; 
n=0:N-1;k=n; 
n=n*dt; 
x=0.15*sin(2*pi*n)+sin(2*pi*2*n)-0.1*sin(2*pi*3*n); 
y=x*exp(-j*2*pi/N).^(n'*k); 
subplot(3,1,1);stem(n,x,'filled');ylabel('x'); 
subplot(3,1,2);stem(k,abs(y),'filled');ylabel('mag X(k)'); 
subplot(3,1,3);stem(k,angle(y),'filled');ylabel('ang X(k)');