n=0:10; 
x=10*0.8.^n; 
N=length(n); 
k=n; 
xr=x(mod(-n,N)+1); 
xe=0.5*(x+xr); 
xo=0.5*(x-xr); 
ye=xe*exp(-j*2*pi/N).^(n'*k); 
yo=xo*exp(-j*2*pi/N).^(n'*k); 
y=x*exp(-j*2*pi/N).^(n'*k); 
errore=max(abs(real(y)-ye)); 
erroro=max(abs(j*imag(y)-yo)); 
subplot(321),stem(n,x);title('x(n)'); 
subplot(322),stem(n,xr);title('x(-n)'); 
subplot(323),stem(n,xe);title('xe(n)'); 
subplot(324),stem(n,xo);title('xo(n)'); 
subplot(325),stem(k,real(y),'xr'); 
hold 
subplot(325),stem(k,ye,'.k');title('real(y)/Xe(k)'); 
subplot(326),stem(k,imag(y),'xr'); 
hold 
subplot(326),stem(k,abs(yo),'.k');title('imag(y)/Xo(k)'); 
figure; 
subplot(121),stem(errore); 
subplot(122),stem(erroro);